'use client';

import { useEffect } from 'react';

export function MermaidRenderer() {
  useEffect(() => {
    let isMounted = true;

    async function renderMermaid() {
      try {
        const mermaidModule = await import('mermaid');
        const mermaid = mermaidModule.default;

        mermaid.initialize({
          startOnLoad: false,
          theme: 'base',
          flowchart: {
            htmlLabels: true,
            useMaxWidth: true,
            curve: 'basis',
          },
          themeVariables: {
            fontFamily: 'Inter, system-ui, sans-serif',
            fontSize: '16px',
            background: '#faf9f6',
            primaryColor: '#ffffff',
            primaryTextColor: '#171717',
            nodeTextColor: '#171717',
            textColor: '#171717',
            primaryBorderColor: '#a3a3a3',
            lineColor: '#737373',
            secondaryColor: '#ffffff',
            tertiaryColor: '#faf9f6',
            secondaryTextColor: '#171717',
            tertiaryTextColor: '#171717',
            edgeLabelBackground: '#faf9f6',
            clusterBkg: '#faf9f6',
            clusterBorder: '#a3a3a3',
            defaultLinkColor: '#737373',
            titleColor: '#171717',
            mainBkg: '#ffffff',
            nodeBorder: '#a3a3a3',
            actorTextColor: '#171717',
            labelTextColor: '#171717',
          },
          securityLevel: 'loose',
        });

        // Find code blocks generated by remark-html
        const elements = document.querySelectorAll('pre code.language-mermaid, pre code.lang-mermaid');

        for (let i = 0; i < elements.length; i++) {
          if (!isMounted) break;
          const element = elements[i];
          const pre = element.parentElement;
          if (!pre || pre.getAttribute('data-mermaid-processed') === 'true') continue;

          pre.setAttribute('data-mermaid-processed', 'true');
          const code = element.textContent || '';
          const uniqueId = `mermaid-svg-${i}-${Math.random().toString(36).substring(2, 9)}`;

          const container = document.createElement('div');
          container.className = 'my-8 p-4 sm:p-6 rounded-xl border overflow-x-auto ltr-force mermaid-wrapper';
          container.style.direction = 'ltr';
          container.setAttribute('dir', 'ltr');
          container.setAttribute('role', 'region');
          container.setAttribute('aria-label', 'Zoomable diagram');
          container.tabIndex = 0;

          try {
            const { svg } = await mermaid.render(uniqueId, code);
            if (isMounted) {
              container.innerHTML = svg;
              const isRtl = document.documentElement.dir === 'rtl';
              const toolbar = document.createElement('div');
              const zoomValue = document.createElement('span');
              const zoomOut = document.createElement('button');
              const zoomIn = document.createElement('button');
              let zoom = 1;

              toolbar.className = 'mermaid-zoom-controls';
              toolbar.setAttribute('role', 'group');
              toolbar.setAttribute('aria-label', isRtl ? 'פקדי הגדלה לתרשים' : 'Diagram zoom controls');

              zoomOut.type = 'button';
              zoomOut.className = 'mermaid-zoom-button';
              zoomOut.textContent = '−';
              zoomOut.setAttribute('aria-label', isRtl ? 'הקטנת התרשים' : 'Zoom out');

              zoomValue.className = 'mermaid-zoom-value';
              zoomValue.setAttribute('aria-live', 'polite');

              zoomIn.type = 'button';
              zoomIn.className = 'mermaid-zoom-button';
              zoomIn.textContent = '+';
              zoomIn.setAttribute('aria-label', isRtl ? 'הגדלת התרשים' : 'Zoom in');

              const updateZoom = () => {
                container.style.setProperty('--mermaid-zoom', String(zoom));
                zoomValue.textContent = `${Math.round(zoom * 100)}%`;
                zoomOut.disabled = zoom === 1;
                zoomIn.disabled = zoom === 3;
              };

              const centerDiagram = () => {
                requestAnimationFrame(() => {
                  container.scrollTo({
                    left: (container.scrollWidth - container.clientWidth) / 2,
                    behavior: 'smooth',
                  });
                });
              };

              zoomOut.addEventListener('click', () => {
                zoom = Math.max(1, zoom - 0.5);
                updateZoom();
                centerDiagram();
              });

              zoomIn.addEventListener('click', () => {
                zoom = Math.min(3, zoom + 0.5);
                updateZoom();
                centerDiagram();
              });

              toolbar.append(zoomOut, zoomValue, zoomIn);
              container.prepend(toolbar);
              updateZoom();
              pre.replaceWith(container);
            }
          } catch (renderError) {
            console.error('Mermaid render error:', renderError);
          }
        }
      } catch (err) {
        console.error('Failed to load mermaid:', err);
      }
    }

    renderMermaid();

    return () => {
      isMounted = false;
    };
  }, []);

  return null;
}
