'use client';

import { useEffect } from 'react';

export function MermaidRenderer() {
  useEffect(() => {
    let isMounted = true;

    async function renderMermaid() {
      try {
        const mermaidModule = await import('mermaid');
        const mermaid = mermaidModule.default;

        mermaid.initialize({
          startOnLoad: false,
          theme: 'dark',
          themeVariables: {
            fontFamily: 'Inter, system-ui, sans-serif',
            primaryColor: '#0f172a',
            primaryTextColor: '#f8fafc',
            primaryBorderColor: '#0284c7',
            lineColor: '#38bdf8',
            secondaryColor: '#1e293b',
            tertiaryColor: '#0f172a',
            edgeLabelBackground: '#1e293b',
          },
          securityLevel: 'loose',
        });

        // Find code blocks generated by remark-html
        const elements = document.querySelectorAll('pre code.language-mermaid, pre code.lang-mermaid');

        for (let i = 0; i < elements.length; i++) {
          if (!isMounted) break;
          const element = elements[i];
          const pre = element.parentElement;
          if (!pre || pre.getAttribute('data-mermaid-processed') === 'true') continue;

          pre.setAttribute('data-mermaid-processed', 'true');
          const code = element.textContent || '';
          const uniqueId = `mermaid-svg-${i}-${Math.random().toString(36).substring(2, 9)}`;

          const container = document.createElement('div');
          container.className = 'my-8 p-6 rounded-2xl bg-slate-900 border border-slate-800 shadow-2xl overflow-x-auto flex justify-center items-center text-slate-100 ltr-force';
          container.style.direction = 'ltr';
          container.setAttribute('dir', 'ltr');

          try {
            const { svg } = await mermaid.render(uniqueId, code);
            if (isMounted) {
              container.innerHTML = svg;
              pre.replaceWith(container);
            }
          } catch (renderError) {
            console.error('Mermaid render error:', renderError);
          }
        }
      } catch (err) {
        console.error('Failed to load mermaid:', err);
      }
    }

    renderMermaid();

    return () => {
      isMounted = false;
    };
  }, []);

  return null;
}
